# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 966f21b4b4e4c1089751b96376244b4f087f29c67da2fffea3a6433219e0bc0c604a2eafdc947eeeb6e7ca5e89377c328a4d04a2d356e74ebde637848afce585

test:
  secret_key_base: fb50f5f4261fd9b1baed63117c25408d803c003aa8aba4fec3087d36075fd912a1ec3d5071a5250ca8228f6c6c3fd5b7301642e21bcf1f4c0697a1bcbf23204c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
